apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "1e003d54-761a-462b-9f6a-95ad8e91a0a9"
      - op: replace
        path: /spec/parameters/tenantId
        value: "2f695754-b89d-4b9b-b341-984f80794ebc"
